mutation createAlbum($input: CreateAlbumInput!) {
    createAlbum(input: $input) {
        title
        id
    }
}

query getUserInfo {
    albums {
        data {
            user {
                name
                id
            }
        }
    }
}
